export const trainers = [
  {
    name: "Piotr Bernat",
    role: "VI dan Taekwon-do · I dan Kickboxing",
    phone: "602 351 585",
    image: "/images/coaches/bernat.jpg",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Prezes",
  },
  {
    name: "Łukasz Staiński",
    role: "II dan Kickboxing · I dan Taekwon-do",
    phone: "787 612 765",
    image: "/images/coaches/stainski.jpg",
    tags: ["Kickboxing", "Taekwon-do", "Technika"],
    position: "Trener",
  },
  {
    name: "Piotr Żołędź",
    role: "II dan Taekwon-do · U3 Kickboxing",
    phone: "609 571 274",
    image: "/images/coaches/zoledz.jpg",
    tags: ["Taekwon-do", "Kickboxing", "Przygotowanie"],
    position: "Trener",
  },
  {
    name: "Bartłomiej Daniel",
    role: "I dan Taekwon-do · U1 Kickboxing",
    phone: "504 814 838",
    image: "/images/coaches/daniel.jpg",
    tags: ["Kickboxing", "Taekwon-do", "Motoryka"],
    position: "Trener",
  },
  {
    name: "Joanna Józefczuk",
    role: "I dan Taekwon-do · U3 Kickboxing",
    phone: "605 302 237",
    image: "/images/coaches/jozefczuk.jpg",
    tags: ["Taekwon-do", "Kickboxing", "Technika"],
    position: "Trener",
  },
  {
    name: "Emilia Szalak",
    role: "I dan Kickboxing",
    phone: "733 222 537",
    image: "/images/coaches/szalak.jpg",
    tags: ["Kickboxing", "Kondycja", "Dynamika"],
    position: "Trener",
  },
];
