export const trainers = [
  {
    name: "Trener 1",
    role: "VI stopień · I dan Kickboxing",
    phone: "600 123 123",
    image: "/placeholder/coach.webp",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Trener",
  },
  {
    name: "Trener 2",
    role: "VI stopień · I dan Kickboxing",
    phone: "600 123 123",
    image: "/placeholder/coach.webp",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Trener",
  },
  {
    name: "Trener 3",
    role: "VI stopień · I dan Kickboxing",
    phone: "600 123 123",
    image: "/placeholder/coach.webp",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Trener",
  },
  {
    name: "Trener 4",
    role: "VI stopień · I dan Kickboxing",
    phone: "600 123 123",
    image: "/placeholder/coach.webp",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Trener",
  },
  {
    name: "Trener 5",
    role: "VI stopień · I dan Kickboxing",
    phone: "600 123 123",
    image: "/placeholder/coach.webp",
    tags: ["Taekwon-do", "Kickboxing", "Mistrzowski poziom"],
    position: "Trener",
  },
];
